# This file is covered by the LICENSE file in the root of this project.
name: "kitti"
labels: 
  0 : "unlabeled"
  1 : "outlier"
  10: "car"
  11: "bicycle"
  13: "bus"
  15: "motorcycle"
  16: "on-rails"
  18: "truck"
  20: "other-vehicle"
  30: "person"
  31: "bicyclist"
  32: "motorcyclist"
  40: "road"
  44: "parking"
  48: "sidewalk"
  49: "other-ground"
  50: "building"
  51: "fence"
  52: "other-structure"
  60: "lane-marking"
  70: "vegetation"
  71: "trunk"
  72: "terrain"
  80: "pole"
  81: "traffic-sign"
  99: "other-object"
  252: "moving-car"
  253: "moving-bicyclist"
  254: "moving-person"
  255: "moving-motorcyclist"
  256: "moving-on-rails"
  257: "moving-bus"
  258: "moving-truck"
  259: "moving-other-vehicle"
color_map: # bgr
  0 : [0, 0, 0]
  1 : [0, 0, 255]
  10: [245, 150, 100]
  11: [245, 230, 100]
  13: [250, 80, 100]
  15: [150, 60, 30]
  16: [255, 0, 0]
  18: [180, 30, 80]
  20: [255, 0, 0]
  30: [30, 30, 255]
  31: [200, 40, 255]
  32: [90, 30, 150]
  40: [255, 0, 255]
  44: [255, 150, 255]
  48: [75, 0, 75]
  49: [75, 0, 175]
  50: [0, 200, 255]
  51: [50, 120, 255]
  52: [0, 150, 255]
  60: [170, 255, 150]
  70: [0, 175, 0]
  71: [0, 60, 135]
  72: [80, 240, 150]
  80: [150, 240, 255]
  81: [0, 0, 255]
  99: [255, 255, 50]
  252: [245, 150, 100]
  256: [255, 0, 0]
  253: [200, 40, 255]
  254: [30, 30, 255]
  255: [90, 30, 150]
  257: [250, 80, 100]
  258: [180, 30, 80]
  259: [255, 0, 0]
content: # as a ratio with the total number of points
  0: 0.018889854628292943
  1: 0.0002937197336781505
  10: 0.040818519255974316
  11: 0.00016609538710764618
  13: 2.7879693665067774e-05
  15: 0.00039838616015114444
  16: 0.0
  18: 0.0020633612104619787
  20: 0.0016218197275284021
  30: 0.00017698551338515307
  31: 1.1065903904919655e-08
  32: 5.532951952459828e-09
  40: 0.1987493871255525
  44: 0.014717169549888214
  48: 0.14392298360372
  49: 0.0039048553037472045
  50: 0.1326861944777486
  51: 0.0723592229456223
  52: 0.002395131480328884
  60: 4.7084144280367186e-05
  70: 0.26681502148037506
  71: 0.006035012012626033
  72: 0.07814222006271769
  80: 0.002855498193863172
  81: 0.0006155958086189918
  99: 0.009923127583046915
  252: 0.001789309418528068
  253: 0.00012709999297008662
  254: 0.00016059776092534436
  255: 3.745553104802113e-05
  256: 0.0
  257: 0.00011351574470342043
  258: 0.00010157861367183268
  259: 4.3840131989471124e-05
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0 : 0     # "unlabeled"
  1 : 0     # "outlier" mapped to "unlabeled" --------------------------mapped
  10: 1     # "car"
  11: 2     # "bicycle"
  13: 3     # "bus" mapped to "other-vehicle" --------------------------mapped
  15: 0     # "motorcycle"
  16: 3     # "on-rails" mapped to "other-vehicle" ---------------------mapped
  18: 3     # "truck" mapped to "other-vehicle" ------------------------mapped
  20: 3     # "other-vehicle"
  30: 4     # "person"
  31: 5     # "bicyclist"
  32: 0     # "motorcyclist"
  40: 6     # "road"
  44: 7     # "parking"
  48: 8     # "sidewalk"
  49: 9     # "other-ground"
  50: 10    # "building"
  51: 11    # "fence"
  52: 0     # "other-structure" mapped to "unlabeled" ------------------mapped
  60: 6     # "lane-marking" to "road" ---------------------------------mapped
  70: 12    # "vegetation"
  71: 13    # "trunk"
  72: 14    # "terrain"
  80: 15    # "pole"
  81: 16    # "traffic-sign"
  99: 0     # "other-object" to "unlabeled" ----------------------------mapped
  252: 1    # "moving-car" to "car" ------------------------------------mapped
  253: 5    # "moving-bicyclist" to "bicyclist" ------------------------mapped
  254: 4    # "moving-person" to "person" ------------------------------mapped
  255: 0    # "moving-motorcyclist" to "motorcyclist" ------------------mapped
  256: 3    # "moving-on-rails" mapped to "other-vehicle" --------------mapped
  257: 3    # "moving-bus" mapped to "other-vehicle" -------------------mapped
  258: 3    # "moving-truck" to "other-vehicle" ------------------------mapped
  259: 3    # "moving-other"-vehicle to "other-vehicle" ----------------mapped
learning_map_inv: # inverse of previous map
  0: 0      # "unlabeled", and others ignored
  1: 10     # "car"
  2: 11     # "bicycle"
  3: 20     # "other-vehicle"
  4: 30     # "person"
  5: 31     # "bicyclist"
  6: 40     # "road"
  7: 44     # "parking"
  8: 48     # "sidewalk"
  9: 49     # "other-ground"
  10: 50    # "building"
  11: 51    # "fence"
  12: 70    # "vegetation"
  13: 71    # "trunk"
  14: 72    # "terrain"
  15: 80    # "pole"
  16: 81    # "traffic-sign"
learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "car"
  2: False     # "bicycle"
  3: False     # "other-vehicle"
  4: False     # "person"
  5: False     # "bicyclist"
  6: False     # "road"
  7: False     # "parking"
  8: False     # "sidewalk"
  9: False     # "other-ground"
  10: False    # "building"
  11: False    # "fence"
  12: False    # "vegetation"
  13: False    # "trunk"
  14: False    # "terrain"
  15: False    # "pole"
  16: False    # "traffic-sign"
split: # sequence numbers
  train:
    - 0
    - 2
    - 3
    - 4
    - 7
    - 10
  valid:
    - 8
  test:
    - 1
    - 5
    - 6
